name: CI & Release Workflow

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Triggers release when pushing versioned tags (e.g., v1.0.0)
  pull_request:
    branches:
      - master

permissions:
  contents: write  # Needed for GitHub Releases
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # `npm ci` is more reliable for CI environments as it installs dependencies based on the package-lock.json

      - name: Install ts-loader
        run: npm install ts-loader --save-dev  # Ensure ts-loader is installed

      - name: Install global tools
        run: |
          npm install -g yo generator-code
          npm install -g @vscode/vsce
          npm install -g webpack webpack-cli

      - name: Build and Package
        run: |
          npx webpack --output-path ./dist
          npx vsce package
        
      - name: Upload .vsix for Release
        run: |
          ls -l # Verify that the .vsix file exists
          echo "Ready to upload .vsix file"

      - name: Upload VSIX file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsix-file
          path: "./*.vsix"  # Upload the .vsix file as an artifact

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Only run for tag-based releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download VSIX file artifact
        uses: actions/download-artifact@v3
        with:
          name: vsix-file  # This should match the artifact name from the build job

      - name: List files before release
        run: |
          echo "Listing files before release"
          ls -l 
        
      - name: Publish to VS Code Marketplace
        run: npx vsce publish --pat ${{ secrets.VSCE_TOKEN }}
        env:
            NODE_AUTH_TOKEN: ${{ secrets.VSCE_TOKEN }}
        continue-on-error: true

      - name: Upload VSIX to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./*.vsix"  # Adjust the path if the .vsix is located elsewhere
          body: "🚀 New release of the VS Code extension!"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}