name: CI Workflow

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write  # ✅ Ensures OIDC authentication works
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install global tools
        run: |
          npm install -g yo generator-code
          npm install -g @vscode/vsce
          npm install -g webpack webpack-cli

      - name: Build and Package
        run: |
          npx webpack
          npx vsce package
  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4