name: CI & Release Workflow

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Triggers release when pushing versioned tags (e.g., v1.0.0)
  pull_request:
    branches:
      - master

permissions:
  contents: write  # Needed for GitHub Releases
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install global tools
        run: |
          npm install -g yo generator-code
          npm install -g @vscode/vsce
          npm install -g webpack webpack-cli

      - name: Build and Package Extension
        run: |
          npx webpack --output-path ./dist
          npx vsce package --out my-extension.vsix

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: my-extension-vsix
          path: my-extension.vsix

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Only run for tag-based releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload VSIX to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: my-extension.vsix
          body: "🚀 New release of the VS Code extension!"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Only run for tag-based releases
    steps:
      - name: Publish to VS Code Marketplace
        run: npx vsce publish --pat ${{ secrets.VSCE_TOKEN }}
